import type { CaseWithRelations } from "@/types";

export const mockCases: CaseWithRelations[] = [
  {
    id: "case-001",
    policyNumber: "POL-2024-001234",
    insuredName: "Budi Santoso",
    status: "NEW",
    description: "Claim for vehicle accident on Jl. Sudirman",
    createdAt: new Date("2024-06-01"),
    updatedAt: new Date("2024-06-01"),
    clientId: "client-001",
    assigneeId: null,
    client: { id: "client-001", name: "PT Asuransi Sejahtera", companyName: "PT Asuransi Sejahtera" },
    assignee: null,
  },
  {
    id: "case-002",
    policyNumber: "POL-2024-005678",
    insuredName: "Siti Rahayu",
    status: "ON_PROGRESS",
    description: "Health claim - hospitalization",
    createdAt: new Date("2024-06-03"),
    updatedAt: new Date("2024-06-05"),
    clientId: "client-001",
    assigneeId: "inv-001",
    client: { id: "client-001", name: "PT Asuransi Sejahtera", companyName: "PT Asuransi Sejahtera" },
    assignee: { id: "inv-001", name: "Ahmad Rizki" },
  },
  {
    id: "case-003",
    policyNumber: "POL-2024-009012",
    insuredName: "Dewi Lestari",
    status: "ON_PROGRESS",
    description: "Property damage - flood claim",
    createdAt: new Date("2024-06-05"),
    updatedAt: new Date("2024-06-08"),
    clientId: "client-002",
    assigneeId: "inv-002",
    client: { id: "client-002", name: "PT Allianz Indonesia", companyName: "PT Allianz Indonesia" },
    assignee: { id: "inv-002", name: "Maria Gunawan" },
  },
  {
    id: "case-004",
    policyNumber: "POL-2024-003456",
    insuredName: "Rudi Hartono",
    status: "ON_PROGRESS",
    description: "Life insurance claim documentation",
    createdAt: new Date("2024-06-07"),
    updatedAt: new Date("2024-06-10"),
    clientId: "client-002",
    assigneeId: "inv-001",
    client: { id: "client-002", name: "PT Allianz Indonesia", companyName: "PT Allianz Indonesia" },
    assignee: { id: "inv-001", name: "Ahmad Rizki" },
  },
  {
    id: "case-005",
    policyNumber: "POL-2024-007890",
    insuredName: "Ani Wijaya",
    status: "ON_PROGRESS",
    description: "Travel insurance - lost baggage",
    createdAt: new Date("2024-06-02"),
    updatedAt: new Date("2024-06-09"),
    clientId: "client-001",
    assigneeId: "inv-002",
    client: { id: "client-001", name: "PT Asuransi Sejahtera", companyName: "PT Asuransi Sejahtera" },
    assignee: { id: "inv-002", name: "Maria Gunawan" },
  },
  {
    id: "case-006",
    policyNumber: "POL-2023-099988",
    insuredName: "Eko Prasetyo",
    status: "CLOSED",
    description: "Motor claim - resolved",
    createdAt: new Date("2024-05-15"),
    updatedAt: new Date("2024-06-01"),
    clientId: "client-001",
    assigneeId: "inv-001",
    client: { id: "client-001", name: "PT Asuransi Sejahtera", companyName: "PT Asuransi Sejahtera" },
    assignee: { id: "inv-001", name: "Ahmad Rizki" },
  },
  {
    id: "case-007",
    policyNumber: "POL-2024-011122",
    insuredName: "Fitri Handayani",
    status: "NEW",
    description: "Fire damage claim - warehouse",
    createdAt: new Date("2024-06-10"),
    updatedAt: new Date("2024-06-10"),
    clientId: "client-002",
    assigneeId: null,
    client: { id: "client-002", name: "PT Allianz Indonesia", companyName: "PT Allianz Indonesia" },
    assignee: null,
  },
  {
    id: "case-008",
    policyNumber: "POL-PRU-2024-1001",
    insuredName: "Hendra Kusuma",
    status: "ON_PROGRESS",
    description: "Critical illness claim - documentation review",
    createdAt: new Date("2024-06-08"),
    updatedAt: new Date("2024-06-11"),
    clientId: "client-003",
    assigneeId: "inv-001",
    client: {
      id: "client-003",
      name: "PT Prudential Life Assurance",
      companyName: "PT Prudential Life Assurance",
    },
    assignee: { id: "inv-001", name: "Ahmad Rizki" },
  },
  {
    id: "case-009",
    policyNumber: "POL-PRU-2024-1002",
    insuredName: "Maya Sari",
    status: "CLOSED",
    description: "Life insurance claim - beneficiary verification",
    createdAt: new Date("2024-06-09"),
    updatedAt: new Date("2024-06-12"),
    clientId: "client-003",
    assigneeId: "inv-002",
    client: {
      id: "client-003",
      name: "PT Prudential Life Assurance",
      companyName: "PT Prudential Life Assurance",
    },
    assignee: { id: "inv-002", name: "Maria Gunawan" },
  },
];

export function getCaseById(id: string): CaseWithRelations | undefined {
  return mockCases.find((c) => c.id === id);
}
